bugsnag/bugsnag-dotnet

Bugsnag.sln
src/Bugsnag.Core/Bugsnag.csproj
src/Bugsnag.Core/Clients/BaseClient.cs
src/Bugsnag.Core/Diagnostics.cs

This is my attempt to make a Mono Compatible version. It basically has a MonoRelease configuration that will remove the incompatible code and references at compile time. It will build `BugsnagMono.dll` so you can tell the difference between the dlls.
I've excluded the incompatible code and reference mentioned in issue #19, but haven't got round to testing it so have no idea if there are any other places which are not compatible. Will try to test it on Mac at some point.

Possible Mono Compatible Version

---

README.md
src/Bugsnag.Core/NotificationFactory.cs
test/Bugsnag.Core.Test/Bugsnag.Test.csproj
test/Bugsnag.Core.Test/FunctionalTests/BasicClientTests.cs
test/Bugsnag.Core.Test/FunctionalTests/ExceptionTypeTests.cs
test/Bugsnag.Core.Test/FunctionalTests/StaticData.cs

An aggregate exception can have multiple inner exceptions. But any of these inner exceptions can be aggregate exceptions themselves. This branching behavior is hard to represent in the current Bugsnag UI, so I've done a fix that end ups generating a new Event whenever this type of branching occurs. 
This isn't ideal but at least records information about every exception generated. The only downside is that its not obvious that two events were created from same Aggregate Exception. Any suggestions on how to represent it in the UI?
Also noticed a bug with displaying inner exceptions...they weren't, they were just copies of the original 
[(link to line)](https://github.com/bugsnag/bugsnag-dotnet/blob/master/src/Bugsnag.Core/NotificationFactory.cs#L132) should be …

Aggregate exceptions + Inner Exception bug

---

src/Bugsnag/Clients/WebMVCClient.cs

Fixes issues #41 
Stops attempting to render a Error page as part of the Bugsnag Client, will just report the exception. 
Note that the exception show now not be marked as handled.

Removed base.OnException() call from MVC client

---

src/Bugsnag/Diagnostics.cs

Only works if app manifest includes supported OS

Detects Windows 10 if added to the app manifest

---

src/Bugsnag/Clients/WebMVCClient.cs

Right now, unhandled exceptions on MVC applications seem to be coming through as warnings. We should be setting those as errors.

Set standard severity for MVC applications

---

build.fsx
src/Bugsnag/Bugsnag.Net35.csproj
src/Bugsnag/Bugsnag.csproj
src/Bugsnag/Clients/BaseClient.cs
src/Bugsnag/Clients/WPFClient.cs
src/Bugsnag/Configuration.cs
src/Bugsnag/ConfigurationStorage/BaseStorage.cs
src/Bugsnag/ConfigurationStorage/ConfigSection.cs
src/Bugsnag/ConfigurationStorage/IConfigurationStorage.cs
src/Bugsnag/Notifier.cs
src/Bugsnag/OfflineStore.cs
test/FunctionalTests/BasicClientTests.cs

This PR allows you to store error reports if they fail to send in IsolatedStorage if the configuration option is set.
If this configuration option is set, then when the Client is started it will attempt to send any stored error reports in a separate thread.

Offline support

---

src/Bugsnag/Payload/Exception.cs
tests/Bugsnag.Tests/Payload/ExceptionTests.cs

Unwrap `AggregateException` so that all of the inner exceptions are reported correctly

improve AggregateException handling

---

src/Bugsnag/Middleware.cs
tests/Bugsnag.AspNet.Tests/ClientTests.cs
tests/Bugsnag.Tests/MiddlewareTests.cs

This changes the context that is set on a report with request information to only use the path of the request. This is in line with [bugsnag-node](https://github.com/bugsnag/bugsnag-node) notifier. This is based on feedback from @jmshal.

Set context with request path

---

src/Bugsnag.AspNet.Core/Middleware.cs
src/Bugsnag.AspNet.WebApi/DelegatingHandler.cs
src/Bugsnag.AspNet/HttpModule.cs
src/Bugsnag.ConfigurationSection/Configuration.cs
src/Bugsnag/Bugsnag.csproj
src/Bugsnag/Client.cs
src/Bugsnag/Configuration.cs
src/Bugsnag/IConfiguration.cs
src/Bugsnag/Middleware.cs
src/Bugsnag/Payload/Exception.cs
src/Bugsnag/Payload/Report.cs
src/Bugsnag/Payload/Session.cs
tests/Bugsnag.AspNet.Tests/ClientTests.cs
tests/Bugsnag.ConfigurationSection.Tests/Bugsnag.ConfigurationSection.Tests.csproj
tests/Bugsnag.ConfigurationSection.Tests/Complete.config
tests/Bugsnag.ConfigurationSection.Tests/CompleteTests.cs
tests/Bugsnag.Tests/ClientTests.cs
tests/Bugsnag.Tests/MiddlewareTests.cs
tests/Bugsnag.Tests/Payload/ReportTests.cs

This changes a few things about the way that ignore classes work
- the configuration now takes actual types instead of strings to ignore
- if any of the exceptions in the report are an instance of a specified type then the whole report is ignored
- in the configuration section we try to obtain the types that have been specified as strings in the config file and ignore them if they do not correspond to a type

Ignore Class behaviour changes

---

src/Bugsnag/Payload/Exception.cs
tests/Bugsnag.Tests/Payload/ExceptionTests.cs

As part of #71 the thrown exception was made the last exception in the list when it should be first. This also expands the tests for inner exceptions and aggregate exceptions to include this constraint

Exception ordering

---

appveyor.yml
build.cake

When a tag is pushed appveyor will now version the nuget packages based on the tag, else it will produce a `dev` tagged version.
This means we can push a tag to release a new version, which pushes correctly versioned nuget packages and creates a GitHub release with the dlls

Improve appveyor integration

---

src/Bugsnag/ThreadQueueDelivery.cs

This was lost during a merge and causes the thread to not be terminated when the application closes

Allow the thread to be terminated

---

CHANGELOG.md
src/Bugsnag/Payload/Event.cs
src/Bugsnag/Payload/HandledState.cs
tests/Bugsnag.Tests/Payload/EventTests.cs
tests/Bugsnag.Tests/Payload/HandledStateTests.cs

While documenting the properties available to before notify callbacks I noticed that the `severity` of the event was missing. This adds in the ability to update the severity of the event during before notify callbacks.

Callback severity changes

---

CHANGELOG.md
src/Bugsnag/Client.cs
src/Bugsnag/Middleware.cs
src/Bugsnag/Payload/Event.cs
tests/Bugsnag.Tests/MiddlewareTests.cs
tests/Bugsnag.Tests/Payload/EventTests.cs

This was raised by @tremlab, the context from the request is not available in the middleware due it being set after the middleware has already been run. This fixes this issue by moving the setting of the context out of the middleware and moving it to being set when the request is updated in the event object.

Improve request context setting

---

CHANGELOG.md
src/Bugsnag/Client.cs
src/Bugsnag/IFilterable.cs
src/Bugsnag/Middleware.cs
src/Bugsnag/Payload/App.cs
src/Bugsnag/Payload/BatchedSessions.cs
src/Bugsnag/Payload/Device.cs
src/Bugsnag/Payload/Metadata.cs
src/Bugsnag/Payload/PayloadExtensions.cs
src/Bugsnag/Payload/Report.cs
src/Bugsnag/Payload/Request.cs
src/Bugsnag/Payload/User.cs
src/Bugsnag/Serializer.cs
src/Bugsnag/SimpleJson.cs
tests/Bugsnag.Tests/PayloadExtensionsTests.cs
tests/Bugsnag.Tests/SerializerTests.cs

- Applies the metadata filtering to all of the required sections of the payload. Previously we were missing both `request` and `user`
- Refactor how filtering is applied
- Apply the metadata filtering to the sessions payload as well

Improve metadata filtering

---

CHANGELOG.md
src/Bugsnag/SessionsStore.cs
tests/Bugsnag.AspNet.Core.Tests/UseExceptionHandlerTests.cs
tests/Bugsnag.AspNet.Core.Tests/WebHostTests.cs
tests/Bugsnag.AspNet.Tests/ClientTests.cs
tests/Bugsnag.AspNet.WebApi.Tests/WebHostTests.cs
tests/Bugsnag.Tests.Server/TestServer.cs
tests/Bugsnag.Tests/ClientTests.cs
tests/Bugsnag.Tests/SessionTrackingTests.cs
tests/Bugsnag.Tests/ThreadQueueDeliveryTests.cs
tests/Bugsnag.Tests/WebRequestTests.cs

Currently even if there has been no session data generated we still send a payload to Bugsnag. If no session data has been generated then we should skip sending the payload
The most substantial change was in the test code. We needed to support providing a timeout to our test server when we are expecting a certain number of requests. This was added so that we could test the scenario above.
The functional change made was to check that session data exists before generating the payload to send.
A test was added that tests when a single session is created that we only see one request to the sessions server.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:

Skip sending empty sessions data payload

---

src/Bugsnag/Middleware.cs
tests/Bugsnag.Tests/MiddlewareTests.cs

Fix the "in project" namespace detection for stack trace lines. (issue #100)
Just change the way StackTraceLine.InProject property is updated and break out of the loop on ProjectNamespaces as soon as the line is detected as in project.
I've done some manual test by sending exception to my bugsnag project
Fixes #100 
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:

Fix InProject namespaces detection

---

src/Bugsnag/Payload/Event.cs
src/Bugsnag/Payload/Report.cs

Do second serialize call only if there is any data being trimmed
Tested by running existing unit tests. No new test added.
`IPayload.Serialize()` returns byte array and `SimpleJson.SerializeObject()` returns string. 
Both will probably cause allocation in Large Object Heap for anything above ~85 KB.
I'm currently facing `OutOfMemoryException` and this is probably one of the contributor.
Better solution should be to serialize to stream. Don't want to depend on existing NuGet package?
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:

Serialization optimization

---

src/Bugsnag/WebRequest.cs

While looking for memory leaks in response to #99 I noticed that in the event that there is an exception while sending a report we continue trying to send the report when we should just stop trying to send the report as we will just get further exceptions if we continue the process. I also noticed that under high load the notify endpoint closes keep alive connections pretty aggressively which results in reports falling to send so I have disabled keep alive on the platforms where we can.
For the submitter, initial self-review:
- This pull request is ready for:
For the pull request reviewer(s), this changeset has been reviewed for:

improved http exception handling

---

CHANGELOG.md
src/Bugsnag.AspNet.WebApi/Bugsnag.AspNet.WebApi.csproj

Adds the configuration package as a dependency of the web api package so that people can use `*.config` files out of the box without having to add the additional package.

Include configuration package

---

CHANGELOG.md
src/Bugsnag.ConfigurationSection/Configuration.cs
tests/Bugsnag.ConfigurationSection.Tests/Complete.config
tests/Bugsnag.ConfigurationSection.Tests/CompleteTests.cs
tests/Bugsnag.ConfigurationSection.Tests/DefaultTests.cs

Allow specifying any kind of exception to ignore in a `config` file. Right now exception types outside of `mscorlib` will not be resolved as you cannot specify the full assembly qualified name which requires the use of a comma which we currently use as a separator.
This adds an additional method of describing ignore classes in a `config` file.

Allow fully qualified types to be provided in config files

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
src/Bugsnag/Payload/StackTraceLine.cs
src/Bugsnag/Polyfills.cs

Prevent a crash when reading code segments from a file fails.
Manually tested locally by forcing an exception and inspecting the stack traces displatyed in the dashboard.

Handle any exceptions raised when reading files for code segments

---

appveyor.yml

Update the (encrypted) API key for publishing to Nuget.  These expire after a year.

Update Nuget (encrypted) API key

---

CHANGELOG.md
src/Bugsnag/Bugsnag.csproj
src/Bugsnag/UnhandledException.cs

Correctly respond to UnobservedTaskExceptions, in terms of whether the process will be terminated.
- For .NET Framework versions prior to 4.5, the process will always terminate.
- For .NET Framework versions after 4.5, the default behavior is not to terminate, but can be configured to do so.  We therefore check for the `ThrowUnobservedTaskExceptions` configuration.
- For .NET Standard we will assume that the default behavior holds - not to terminate
Tested with the standard regression tests, together with manual testing using the examples in the repository.
Assuming that the process will not terminate with .NET Standard is not ideal, as it could be configured to do so.  However, determining how to check the configuration in a portable way has proven troublesome and so we will address this …

Unobserved exception handling

---

UPGRADING.md

WPF applications should use v1.4.0, as per the docs. The upgrade guide should not contain any instruction for WPF applications.

Removed WPF from UPGRADING.md

---

README.md

Adds a link to the license file for consistency with other notifiers.

docs(readme): adds license file link in readme

---

src/Bugsnag/UnhandledException.cs

for .NET 4.5 Bugsnag attempts to load the `App.config` file to read the value of the `ThrowUnobservedTaskExceptions` element and this crashes with a `FileNotFoundException` if there is no `App.config` file. This PR guards against `App.config` not existing
Make sure that the file exists before loading, and assume the default behaviour (UnobservedTaskExceptions do not terminate the process) if the config file doesn't exist.
Added a `File.Exists` check to `UnhandledException#DetermineUnobservedTerminates`
Ran the unit tests and tested manually using the example apps in the repository

PLAT-5359] Assume default behaviour for UnobservedTaskExceptions when app.config does not exist

---

src/Bugsnag/Middleware.cs
src/Bugsnag/Payload/StackTraceLine.cs
tests/Bugsnag.Tests/MiddlewareTests.cs

Fixes a crash in the notifier when a Stackframe reports a `null` method.
It's possible that `StackFrame.GetMethod()` may return `null` in some circumstances, so we should guard against this in our code
Added null checks wherever code accesses `StackTraceLine.Methodname`
Tested manually by manipulating stacktraces in the debugger to cause a crash.

Fix crash when stackframe method is null

---

examples/netcore11-console/Program.cs

Updates the .NET Core 1.1 example Console app to ensure the app stays alive long enough for the report to be sent. 
Looks like this is due to a limitation of .NET Core 1.1. Delivery is done on a background thread, and although this is dequeued immediately the console app is terminated before the background thread has finished sending the report. This is not the case in .NET Core 2.0.
As .NET Core 1.1 is EOL and not widely used I don't think this is worth investigating further, and we should simply prevent the console app from exiting immediately. 
Adds a `Console.ReadKey()` to the example to ensure the app stays alive long enough for the report to be sent
Tested manually running the example app both from within Visual Studio and using the dotnet CLI.

Fix .NET Core 1.1 example

---

appveyor.yml
build.cake

Currently Appveyor attempts to upload the `nupkg` build artifacts to `nuget.org` and the `.symbols.nupkg` artifacts to the 3rd party symbol server `nuget.symbsrc.net`, which is no longer maintained. NuGet now supports publishing symbol packages directly to NuGet, using the new `snupkg` package format.
Updates the build to create NuGet symbol packages using the new `.snupkg` format rather than the now legacy `.symbols.nupkg` format, and configures Appveyor publish these to `nuget.org` rather than the 3rd-party `smbsrc.net`.

Switch to snupkg package format and publish symbols to nuget.org

---

Directory.build.props
src/Directory.build.props
tests/Directory.build.props

As part of #151 the strong naming signing build properties were added to the root `Directory.build.props` which was then imported into `src/Directory.build.props`. 
However the root props also contains a `BaseOutputPath` property so this altered the output path for all of the project builds, so the post-build ZIP command was unable to locate the assemblies, leading to an empty `bugsnag.zip` artefact being uploaded to GitHub
Moved strong naming config out of the root props so that the `BaseOutputPath` is no longer imported by all projects. Also had to tweak `test/Directory.build.props` to ensure the tests preserved the same output path as before
Manually tested build output against v2.2.3 to ensure output path was reverted and manually tested ZIP command to ensure that assemblies are …

[PLAT-8150] Fix empty bugsnag.zip build artefact

---

appveyor.yml

Regenerated the expired nuget API key and updated the appveyor config with the new (encrypted) key

Update nuget API key

---

src/Bugsnag.AspNet.Core/Bugsnag.AspNet.Core.csproj
src/Bugsnag.AspNet.Mvc/Bugsnag.AspNet.Mvc.csproj
src/Bugsnag.AspNet.WebApi/Bugsnag.AspNet.WebApi.csproj
src/Bugsnag.AspNet/Bugsnag.AspNet.csproj
src/Bugsnag.ConfigurationSection/Bugsnag.ConfigurationSection.csproj
src/Bugsnag/Bugsnag.csproj
src/Bugsnag/UnhandledException.cs
src/Directory.build.props
tests/Bugsnag.AspNet.Core.Tests/Bugsnag.AspNet.Core.Tests.csproj

Adds a net6.0 target framework for the Bugsnag and Bugsnag.AspNet.Core packages and updates project references accordingly.
Many of the package references (nuget dependencies) for these projects are provided by the .NET platform/framework and only require a nuget package reference when targeting netstandard. 
By targeting net6.0 and restricting these package references to the netstandard2.0 target, consuming projects on .NET 6+ will not need to pull in unnecessary nuget dependencies for packages that are provided by the platform/runtime, while projects that still need to use the netstandard2.0 dll can continue to do so.
In addition, I've removed the `DisableImplicitFrameworkReferences` config and removed unnecessary framework references from the project files. This was an outdated …

Add net6.0 target framework for Bugsnag and Bugsnag.AspNet.Core

---

src/Bugsnag.AspNet.Core/Extensions.cs
src/Bugsnag.AspNet/Client.cs
src/Bugsnag/Client.cs

Configuring a proxy requires creating a new `HttpClient` because the `HttpClientHandler` (which handles the proxy settings) cannot be modified once the `HttpClient` is created.
This PR improves the handling of the delivery configuration for request scoped clients to ensure that `HttpClient` instances are not unnecessarily disposed and recreated for each request when a proxy is specified.
Added a new client constructor overload to support creating clients with a preconfigured delivery instance, and updated the logic in `Bugsnag.AspNet` and `Bugsnag.AspNet.Core` to use this and configure delivery once on startup
Tested manually

Ensure delivery is only configured once for request scoped clients

---

src/Bugsnag/Serializer.cs
tests/Bugsnag.Tests/SerializerTests.cs

Make `MetadataFilters` case insensitive, as per the notifier spec for redacted keys. 
Filters are converted to a dictionary in the serializer, so this just needed updating to use case insensitive key comparison.
Added a new unit test case to verify that filtering is case insensitive

Make MetadataFilters case insensitive
